# Generated by Django 3.1.6 on 2021-02-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postname',
            new_name='title',
        ),
    ]
